### ISSUE TITLE
No train/test for whole of question 2?

### ISSUE THREAD

**Issue by BasBijlsma** [lse-me314/finalexam#2]
Hi Ken, at the bottom of question 2 it is written that 

> **Note:** You do not have to split the data into test and training sets here.  Just predict on the training sample, which consists of the entire dataset.

Does this **Note** refer to the whole question 2 (parts a, b and c) or only to bonus part c?

Thanks, Bas

**Comment by sjankin** [comment]
The note refers to bonus part c (fitting a naive bayes classifier).
